export const content = {
  ar: {
    dir: "rtl",
    nav: {
      home: "الرئيسية",
      services: "الخدمات",
      industries: "القطاعات",
      portfolio: "أعمالنا",
      pricing: "الأسعار",
      about: "عن الشركة",
      contact: "تواصل معنا",
      cta: "احصل على عرض مجاني",
      servicesMenu: [
        { icon: "🤖", title: "الذكاء الاصطناعي", desc: "نماذج مخصصة لتوليد المحتوى" },
        { icon: "💻", title: "تطوير البرمجيات", desc: "تطبيقات المؤسسات المخصصة" },
        { icon: "🌐", title: "تطوير المواقع", desc: "تجارب رقمية باهرة" },
        { icon: "📱", title: "تطبيقات الجوال", desc: "iOS وAndroid بأداء محلي" },
        { icon: "☁️", title: "الخدمات السحابية", desc: "AWS وAzure وGoogle Cloud" },
        { icon: "🔒", title: "الأمن السيبراني", desc: "حماية المؤسسات والامتثال" },
        { icon: "🎨", title: "تصميم UX/UI", desc: "واجهات حائزة على جوائز" },
        { icon: "📊", title: "تحليل البيانات", desc: "ذكاء الأعمال والتنبؤ" },
        { icon: "⚙️", title: "أنظمة ERP/CRM", desc: "تكامل أنظمة المؤسسات" },
        { icon: "🔁", title: "DevOps والأتمتة", desc: "CI/CD والحاويات" },
        { icon: "🚀", title: "التحول الرقمي", desc: "تحديث شامل للمؤسسات" },
        { icon: "🤝", title: "استشارات تقنية", desc: "التخطيط الاستراتيجي" },
      ],
      industriesMenu: [
        { icon: "🏥", title: "الرعاية الصحية", desc: "أنظمة الصحة الرقمية" },
        { icon: "🏦", title: "المصارف والمالية", desc: "منصات FinTech" },
        { icon: "🏛️", title: "الحوكمة والقطاع العام", desc: "المدن الذكية والحوكمة" },
        { icon: "🛍️", title: "التجزئة والتجارة", desc: "منصات متعددة القنوات" },
        { icon: "🎓", title: "التعليم والتدريب", desc: "منصات التعلم الإلكتروني" },
        { icon: "⚡", title: "الطاقة والبتروكيماويات", desc: "حلول الشبكات الذكية" },
      ],
    },
    hero: {
      badge: "موثوق من قبل أكثر من 200 مؤسسة إقليمية",
      h1a: "نبني",
      h1gold: "مستقبل أعمالك",
      h1b: "بالذكاء الاصطناعي",
      sub: "حلول ذكاء اصطناعي وسحابية ورقمية بمستوى المؤسسات، مصممة لعصر رؤية 2030. من الأتمتة الذكية إلى البرمجيات العالمية المستوى.",
      btn1: "ابدأ مشروعك ←",
      btn2: "▶ شاهد أعمالنا",
      stats: [
        { n: "+200", l: "عميل مؤسسي" },
        { n: "%98", l: "رضا العملاء" },
        { n: "+12", l: "سنة خبرة" },
      ],
      float1: "نشر نموذج AI بنجاح",
      float2: "نمو الإيرادات +340%",
      float3: "تشغيل 99.9%",
      dashTitle: "لوحة ذكاء نيكسا كور المتقدمة",
      dml1: "طلبات AI",
      dml2: "الدقة",
      dml3: "التوفير",
      dch: "حجم معالجة AI — آخر 7 أيام",
      daiTitle: "المساعد الذكي نشط",
      daiMsg: "تم اكتشاف وحل الخلل تلقائيًا — منذ 3 ثوانٍ",
    },
    trusted: "أسماء تشكّل الاقتصاد الرقمي في المنطقة",
    trustedSub: "نظرة على المؤسسات والوزارات والمنصات التي تقود قطاعات الأعمال والتمويل والخدمات العامة في المملكة العربية السعودية ودول الخليج.",
    services: {
      tag: "ما نقدمه",
      title: 'تميز رقمي <em>شامل من الألف إلى الياء</em>',
      sub: "من الذكاء الاصطناعي إلى تطبيقات الجوال والبنية السحابية — كل حل مصمم لمقياس المؤسسات الكبرى.",
      items: [
        { icon: "🤖", title: "الذكاء الاصطناعي والتعلم الآلي", desc: "نماذج AI مخصصة لمعالجة اللغة الطبيعية ورؤية الحاسوب وحلول GenAI مدربة على بياناتك." },
        { icon: "💻", title: "تطوير البرمجيات", desc: "تطبيقات مؤسسية بهندسة معمارية حديثة — قابلة للتوسع وآمنة ومستعدة للمستقبل." },
        { icon: "🌐", title: "تطوير المواقع الإلكترونية", desc: "تجارب رقمية باهرة باستخدام Next.js وReact وأحدث تقنيات الواجهة الأمامية." },
        { icon: "📱", title: "تطبيقات الجوال", desc: "تطبيقات iOS وAndroid متعددة المنصات تحبها المستخدمون بأداء محلي وتصميم أنيق." },
        { icon: "☁️", title: "السحابة وDevOps", desc: "بنية AWS وAzure وGCP مع خطوط CI/CD وKubernetes واتفاقيات خدمة بنسبة 99.99%." },
        { icon: "🔐", title: "الأمن السيبراني", desc: "اختبار الاختراق وعمليات SOC وأطر الامتثال وفق المعايير التنظيمية الإقليمية." },
        { icon: "🎨", title: "تصميم UI/UX", desc: "واجهات حائزة على جوائز مبنية على بحث المستخدم ومبادئ UX العربية الدقيقة." },
        { icon: "📈", title: "البيانات والتحليلات", desc: "لوحات ذكاء الأعمال ومستودعات البيانات والتحليلات التنبؤية على نطاق المؤسسات." },
      ],
    },
    video: {
      h2a: "نبني مواقع وتطبيقات",
      h2em: "تغيّر قواعد اللعبة",
      p: "12 عامًا من التميز في تطوير البرمجيات والمواقع والتطبيقات — أكثر من 850 مشروعًا تم تسليمها لأبرز المؤسسات في المنطقة.",
      cta: "احجز استشارة مجانية ←",
    },
    ai: {
      tag: "حلول الذكاء الاصطناعي",
      titleA: "حلول",
      titleEm: "ذكاء اصطناعي متقدمة",
      titleB: "لسوق المنطقة",
      sub: "ننشر حلول AI جاهزة للإنتاج تفهم اللغة العربية والثقافة المحلية وسياق الأعمال الإقليمي — وليست نسخ نماذج عامة.",
      features: [
        { icon: "🧠", h: "نماذج اللغة العربية أولاً", p: "نماذج لغوية مضبوطة بدقة للهجات العربية والفصحى مع سياق أعمال محلي." },
        { icon: "👁️", h: "رؤية الحاسوب", p: "التعرف على المستندات والتحقق من الهوية وفحص البنية التحتية — مدرب على بيانات إقليمية." },
        { icon: "⚡", h: "وكلاء AI والأتمتة", p: "وكلاء مستقلون يتعاملون مع سير العمل وخدمة العملاء واتخاذ القرار على مدار الساعة." },
        { icon: "🔮", h: "التحليلات التنبؤية", p: "نماذج التنبؤ لتخطيط الطلب وكشف الاحتيال وإدارة المخاطر." },
      ],
    },
    mosaic: {
      tag: "من وراء الكواليس",
      title: "فريق يبني <em>الاستثنائي</em>",
      labels: ["مركز بيانات متطور", "فريق التطوير", "ذكاء اصطناعي متقدم", "اجتماعات العملاء", "خوادم سحابية"],
    },
    sectors: {
      tag: "القطاعات الرئيسية",
      title: "نخدم <em>أهم القطاعات</em><br>في الاقتصاد الإقليمي",
      sub: "خبرة موثقة عبر أكثر من 12 قطاعًا حيويًا تشكل ركائز التنمية الاقتصادية.",
      left: [
        { h: "قطاع الرعاية الصحية", p: "أنظمة صحية رقمية، سجلات طبية إلكترونية، وAI تشخيصي" },
        { h: "الهندسة والإنشاءات", p: "إدارة مشاريع ذكية، BIM، ومنصات المقاولات الرقمية" },
        { h: "القطاع القانوني", p: "أتمتة العقود، الإدارة القانونية، وحلول الامتثال التنظيمي" },
        { h: "السلامة والجودة", p: "أنظمة إدارة الجودة، التفتيش الذكي، وضمان المطابقة" },
        { h: "الصناعة والتصنيع", p: "أتمتة المصانع، IoT الصناعي، وإدارة سلاسل الإمداد" },
        { h: "الطاقة والبتروكيماويات", p: "إدارة العمليات، مراقبة الشبكات، وتحليلات الطاقة" },
      ],
      right: [
        { h: "التقنية والتحول الرقمي", p: "حلول AI، تطوير البرمجيات، والبنية التحتية الرقمية" },
        { h: "المصارف والخدمات المالية", p: "FinTech، بنوك رقمية، وأنظمة المدفوعات الإلكترونية" },
        { h: "قطاع التعليم والتدريب", p: "منصات تعلم ذكية، LMS، وتقنيات التعليم التفاعلي" },
        { h: "اللوجستيات والنقل", p: "تتبع الشحنات، إدارة الأسطول، وتحسين سلاسل التوريد" },
        { h: "العقارات والإسكان", p: "منصات إدارة العقارات، VR للجولات، وتقييم ذكي" },
        { h: "التجزئة والتجارة الإلكترونية", p: "متاجر إلكترونية، تجارة متعددة القنوات، وتوصيات AI" },
      ],
    },
    industries: {
      tag: "القطاعات",
      title: "نخدم كل <em>قطاع</em>",
      sub: "خبرة عميقة عبر الصناعات التي تدفع عجلة الاقتصاد الإقليمي.",
      items: ["الرعاية الصحية", "المصارف والمالية", "الحوكمة", "التجزئة", "البناء والمقاولات", "التعليم", "الصناعة والتصنيع", "الضيافة والسياحة", "اللوجستيات والنقل", "الطاقة والبتروكيماويات", "العقارات", "الاتصالات"],
      icons: ["🏥", "🏦", "🏛️", "🛍️", "🏗️", "🎓", "🏭", "🏨", "🚚", "⚡", "🏠", "📡"],
    },
    stats: [
      { target: 200, suffix: "+", label: "عميل مؤسسي" },
      { target: 12, suffix: "+", label: "سنة تميز" },
      { target: 850, suffix: "+", label: "مشروع مُسلَّم" },
      { target: 98, suffix: "%", label: "رضا العملاء" },
    ],
    values: {
      tag: "قيمنا الجوهرية",
      title: "مبادئ تحكم كل <em>قرار نتخذه</em>",
      sub: "ليست مجرد كلمات على جدار — هي الإطار الذي يشكل كل مشروع ننفذه وكل علاقة نبنيها.",
      items: [
        { h: "الثقة والموثوقية", p: "نضع مصالح عملائنا دائمًا في المقدمة، ونلتزم بالشفافية الكاملة في كل خطوة." },
        { h: "الخبرة العالمية", p: "فريق متخصص من أكثر من 16 دولة يجمع أفضل الممارسات العالمية مع الفهم المحلي العميق." },
        { h: "الجودة والدقة", p: "من تصفية سطر كود واحد إلى بناء عمليات تحول عملاء — نعرف بالجودة لا بالتخمين." },
        { h: "التحسين المستمر", p: "نواكب التغيير ونتبنى أفضل الممارسات — لأن التكنولوجيا لا تتوقف، ولا نحن كذلك." },
      ],
    },
    certs: {
      tag: "معايير موثوقة",
      title: "ملتزمون <em>بأعلى معايير</em><br>الجودة والامتثال",
      sub: "شهادات واعتمادات دولية تضمن أعلى مستويات الجودة والأمان والموثوقية في كل مشروع.",
      items: [
        { title: "أيزو 27001", sub: "إدارة أمن المعلومات" },
        { title: "SOC 2 Type II", sub: "ضوابط أمنية معتمدة" },
        { title: "حماية البيانات", sub: "امتثال كامل للخصوصية" },
        { title: "PCI DSS", sub: "أمان بيانات المدفوعات" },
        { title: "ISO 9001", sub: "إدارة الجودة الشاملة" },
        { title: "تحالف أمن السحابة", sub: "معايير الحوسبة السحابية" },
        { title: "اختبار اختراق سنوي", sub: "تدقيق أمني مستقل" },
        { title: "اتفاقيات SLA", sub: "ضمان مستوى الخدمة" },
      ],
    },
    pricing: {
      tag: "خطط الأسعار",
      title: "أسعار شفافة <em>لكل حجم أعمال</em>",
      sub: "باقات مصممة خصيصًا للسوق السعودي — نطاق واضح، ومخرجات محددة، وبدون رسوم خفية.",
      note: "* جميع الأسعار بالريال السعودي (SAR) ولا تشمل ضريبة القيمة المضافة 15%. الأسعار ابتداءً من وتختلف حسب نطاق المشروع.",
      popular: "الأكثر طلبًا",
      priceFrom: "ابتداءً من",
      currency: "ريال",
      plans: [
        {
          name: "الأساسية",
          desc: "مثالية للشركات الناشئة والأعمال الصغيرة التي تبدأ رحلتها الرقمية.",
          price: "12,000",
          features: [
            "موقع إلكتروني احترافي متجاوب (حتى 5 صفحات)",
            "تصميم UI/UX مخصص باللغتين العربية والإنجليزية",
            "تحسين أساسي لمحركات البحث (SEO)",
            "استضافة سحابية لمدة 3 أشهر",
            "دعم فني لمدة 30 يومًا",
          ],
          cta: "ابدأ الآن",
        },
        {
          name: "النمو",
          desc: "للشركات المتنامية التي تحتاج منصة رقمية متكاملة أو متجرًا إلكترونيًا.",
          price: "35,000",
          features: [
            "تطبيق ويب أو متجر إلكتروني متكامل",
            "لوحة تحكم إدارية مخصصة",
            "تكامل بوابات الدفع السعودية (مدى، STC Pay)",
            "تحسين متقدم لمحركات البحث",
            "دعم وصيانة لمدة 6 أشهر",
          ],
          cta: "ابدأ الآن",
        },
        {
          name: "المؤسسات",
          desc: "حلول برمجية مؤسسية متكاملة مع تكامل الأنظمة وبنية سحابية قابلة للتوسع.",
          price: "95,000",
          highlight: true,
          features: [
            "تطبيق ويب/جوال مؤسسي مخصص",
            "تكامل أنظمة ERP/CRM",
            "بنية سحابية على AWS أو Azure",
            "أمن سيبراني وامتثال ISO 27001",
            "مدير حساب مخصص واتفاقية SLA لمدة 12 شهرًا",
          ],
          cta: "احجز استشارة",
        },
        {
          name: "الذكاء الاصطناعي والأتمتة",
          desc: "حلول ذكاء اصطناعي مخصصة — من روبوتات المحادثة إلى نماذج مدربة على بياناتك.",
          price: "150,000",
          features: [
            "نماذج AI / LLM مخصصة باللغة العربية",
            "أتمتة العمليات وسير العمل (RPA)",
            "تكامل رؤية الحاسوب أو معالجة اللغة الطبيعية",
            "لوحات تحليلات تنبؤية",
            "دعم وتدريب مستمر لمدة 12 شهرًا",
          ],
          cta: "تحدث مع خبير",
        },
      ],
      custom: {
        title: "تحتاج برنامج تحول رقمي شامل؟",
        desc: "باقة \"المؤسسات الكبرى\" مصممة خصيصًا للجهات الحكومية والمؤسسات الكبرى — نطاق مشروع مخصص بالكامل، فريق ومدير برنامج مخصص، اتفاقيات SLA مخصصة، ومتطلبات إقامة بيانات وامتثال محلي.",
        cta: "تواصل معنا لعرض سعر مخصص ←",
      },
    },
    why: {
      tag: "لماذا نيكسا كور",
      title: "المعيار الذي<br>يطمح إليه <em>الآخرون</em>",
      items: [
        { n: "01", icon: "🌍", h: "هوية إقليمية أصيلة", p: "وُلدنا وبنينا فرقنا في المنطقة. نفهم متطلبات الامتثال المحلية وخصوصيات ممارسة الأعمال." },
        { n: "02", icon: "⚡", h: "سرعة دون تنازل", p: "ننفذ بسرعة 3 أضعاف الوكالات التقليدية دون المساس بالجودة. سبرنت أسبوعية ونماذج سريعة." },
        { n: "03", icon: "💬", h: "تصميم قائم على البحث", p: "كل واجهة مدعومة بأبحاث المستخدمين واختبارات A/B وبيانات التحويل." },
        { n: "04", icon: "🛡️", h: "أمن على مستوى المؤسسات", p: "عمليات معتمدة بـISO 27001 والتزام SOC 2 Type II وبنية تحتية مختبرة بالاختراق." },
        { n: "05", icon: "🌐", h: "فريق عالمي بروح محلية", p: "أكثر من 150 مهندسًا ومصممًا وباحثًا في AI — بثقافة عربية أصيلة ومعايير تقنية عالمية." },
        { n: "06", icon: "🎯", h: "دعم مخصص ومستمر", p: "مدير حساب مخصص ومراقبة على مدار الساعة وأوقات استجابة مضمونة باتفاقيات SLA." },
      ],
    },
    team: {
      tag: "فريقنا",
      title: "نخبة عالمية<br><em>بروح إقليمية</em>",
      intro: '<strong>نيكسا كور</strong> يقودها مستشارون محليون وإقليميون على رأس فريق عالمي من المواهب من أكثر من <strong>16 جنسية</strong>، يحملون شهادات واعتمادات دولية تؤهلنا للمنافسة على أعلى المستويات العالمية.',
      countries: ["المملكة العربية السعودية", "الإمارات العربية المتحدة", "الكويت", "البحرين", "قطر", "سلطنة عمان", "مصر", "لبنان", "الأردن", "الولايات المتحدة", "المملكة المتحدة", "البرتغال", "الصين", "إسبانيا", "تركيا", "إيطاليا", "ألمانيا", "الهند"],
      flags: ["sa", "ae", "kw", "bh", "qa", "om", "eg", "lb", "jo", "us", "gb", "pt", "cn", "es", "tr", "it", "de", "in"],
      stats: [
        { n: "+150", l: "عضو في الفريق" },
        { n: "+16", l: "جنسية مختلفة" },
        { n: "+45", l: "شهادة معتمدة دوليًا" },
        { n: "+12", l: "سنة خبرة مشتركة" },
      ],
    },
    portfolio: {
      tag: "معرض الأعمال",
      title: "أعمال <em>تتحدث</em> عن نفسها",
      sub: "مختارات من أبرز مشاريعنا المؤسسية في المنطقة.",
      featured: [
        {
          name: "Go Mobility",
          tagline: "تطبيق النقل التشاركي الأول في الهند الذي يضع السائق أولاً",
          tag: "النقل التشاركي · تطبيق جوال · دلهي الكبرى",
          desc: "منصة نقل تشاركي ثنائية الاتجاه مصممة للسائقين والركاب على حد سواء — بدون رسوم إلغاء، وتتبع GPS مباشر، ودعم SOS، ونموذج صفر عمولة للسائقين مع رسوم منصة يومية محدودة. تنطلق في دلهي وغورغاون ونويدا وغازي آباد وفريد آباد.",
          features: [
            "بدون رسوم إلغاء وتسعير شفاف بالكامل",
            "سائقون موثقون مع فحص المركبات من 20 نقطة",
            "تتبع GPS مباشر ودعم SOS للسلامة",
            "عمولة صفر للسائقين وتحويلات بنكية يومية",
            "دعم فني بالهندية على مدار الساعة",
          ],
          link: "https://www.gomobility.co.in/",
          linkLabel: "زيارة الموقع الإلكتروني ←",
          qrLabel: "امسح لتحميل التطبيق",
          logo: "/portfolio/go-mobility-logo.jpg",
          qr: "/portfolio/go-mobility-qr.png",
        },
        {
          name: "Golden Clouds Consulting",
          tagline: "تأهيل المؤسسات لأعلى المعايير الدولية",
          tag: "استشارات إدارية · استراتيجية · جدة",
          desc: "شركة استشارات سعودية بخبرة تتجاوز 30 عامًا، تساعد المؤسسات على النمو عبر الاستراتيجية والحوكمة ورأس المال البشري — بدعم من أكثر من 130 شراكة استراتيجية وتحالفات مع ديلويت وPwC وEY وKPMG.",
          features: [
            "أكثر من 100 عام من الخبرة الاستشارية المجمعة",
            "فريق عالمي من أكثر من 16 جنسية و9 لغات",
            "أكثر من 130 شراكة استراتيجية حول العالم",
            "متوافقة مع برامج رؤية السعودية 2030",
            "حضور في أكثر من 10 دول",
          ],
          link: "https://gccso.com/en/",
          linkLabel: "زيارة الموقع الإلكتروني ←",
          logo: "/portfolio/golden-clouds-consulting.jpg",
        },
        {
          name: "Smart Homes",
          tagline: "امتلك الذكاء — نحوّل المباني إلى مساحات ذكية",
          tag: "أتمتة المنازل الذكية · إنترنت الأشياء · السعودية",
          desc: "شركة سعودية متخصصة في المباني الذكية تقدم أتمتة المنازل، وأنظمة التنظيف المركزي والغاز، وتسخين المياه بالطاقة الشمسية، وأنظمة أمنية مدمجة بالذكاء الاصطناعي — منتشرة في أكثر من 6,000 وحدة سكنية و13 منطقة بالمملكة.",
          features: [
            "أكثر من 45,000 منتج ذكي مُركّب على مستوى المملكة",
            "أكثر من 6,000 وحدة سكنية تم تحويلها لمنازل ذكية",
            "أكثر من 5,000 نظام تنظيف مركزي منفَّذ",
            "مراقبة أمنية مشفّرة على مدار الساعة",
            "أكثر من 5 فروع في أنحاء المملكة",
          ],
          link: "https://www.smarthomes.sa/",
          linkLabel: "زيارة الموقع الإلكتروني ←",
          logo: "/portfolio/smart-homes.jpg",
        },
      ],
      items: [
        { tag: "تقنية مالية · ذكاء اصطناعي", name: "منصة مصرفية رقمية — عميل سري", icon: "🏦", desc: "منصة خدمات مصرفية رقمية متكاملة مع كشف احتيال بالذكاء الاصطناعي وتوصيات مالية مخصصة." },
        { tag: "رعاية صحية · جوال", name: "تطبيق صحة وطني — عميل سري", icon: "🏥", desc: "تطبيق جوال وطني يربط المرضى بالمرافق الصحية، حجز المواعيد، والسجلات الطبية الإلكترونية." },
        { tag: "مدينة ذكية · IoT", name: "بنية تحتية ذكية بالذكاء الاصطناعي — عميل سري", icon: "🏙️", desc: "شبكة استشعار IoT مع تحليلات AI لإدارة المرور والطاقة والخدمات الحضرية في الوقت الفعلي." },
        { tag: "طاقة · تحليلات", name: "لوحة عمليات الطاقة — عميل سري", icon: "⚡", desc: "لوحة تحكم تشغيلية موحدة لمراقبة الشبكات ومحطات الطاقة والتنبؤ بالصيانة." },
        { tag: "تعليم إلكتروني · LMS", name: "منصة التعلم الوطنية — عميل سري", icon: "📚", desc: "منصة تعلم إلكتروني متعددة اللغات تخدم مئات الآلاف من الطلاب بمحتوى تفاعلي وتتبع أداء." },
        { tag: "تجزئة · تجارة إلكترونية", name: "منصة تجارة موحدة إقليمية — عميل سري", icon: "🛒", desc: "منصة تجارة موحدة عبر القنوات تجمع المتجر الإلكتروني ونقاط البيع والمخزون في نظام واحد." },
        { tag: "لوجستيات · تتبع الأسطول", name: "منصة إدارة الأسطول واللوجستيات — عميل سري", icon: "🚚", desc: "نظام تتبع أسطول حي مع تحسين المسارات بالذكاء الاصطناعي وإدارة سلاسل الإمداد الإقليمية." },
      ],
    },
    process: {
      tag: "كيف نعمل",
      title: "منهجيتنا <em>المُثبتة</em>",
      sub: "إطار تسليم محكم أثبت نجاحه مع أكثر من 200 مؤسسة — من المكالمة الأولى إلى الإطلاق النهائي.",
      steps: [
        { icon: "🔍", h: "الاستكشاف", p: "متطلبات معمقة ومقابلات أصحاب المصلحة وتدقيق تقني وبحث في السوق." },
        { icon: "✏️", h: "الاستراتيجية والتصميم", p: "الهندسة المعمارية، النماذج الأولية، نظام التصميم، والموافقة على النماذج." },
        { icon: "⚙️", h: "التطوير", p: "سبرنت رشيقة مع عروض أسبوعية ومراجعات كود وتكامل مستمر." },
        { icon: "🧪", h: "ضمان الجودة", p: "الأداء والأمان عبر الأجهزة واختبار القبول مع مستخدمين حقيقيين." },
        { icon: "🚀", h: "الإطلاق والنمو", p: "الإطلاق والمراقبة والتحسين والشراكة المستمرة." },
      ],
    },
    tech: {
      tag: "التقنيات",
      title: "نبني بأفضل <em>الأدوات المتاحة</em>",
      sub: "من الواجهة الأمامية إلى البنية التحتية للخوادم — مكدس تقني حديث ومختبر في الإنتاج، يشمل خوادم وقواعد بيانات وأدوات DevOps على مستوى المؤسسات.",
      hubLabel: "النواة التقنية",
      hubHint: "مرر للأسفل لترى كيف يتصل كل شيء ببعضه ←",
      categories: {
        all: "الكل",
        frontend: "الواجهة الأمامية",
        backend: "الخوادم والبرمجة الخلفية",
        database: "قواعد البيانات",
        cloud: "السحابة وDevOps",
        ai: "الذكاء الاصطناعي",
      },
    },
    testimonials: {
      tag: "آراء عملائنا",
      title: "ماذا يقول <em>عملاؤنا</em> عنا",
      items: [
        { q: "نيكسا كور حولت عملياتنا الرقمية بالكامل. حل الذكاء الاصطناعي الذي بنوه خفّض وقت المعالجة لدينا بنسبة 80% وبدقة لا مثيل لها. فريق محترف على مستوى المؤسسات.", name: "أحمد الفهد", role: "المدير التقني، مجموعة فالكون القابضة" },
        { q: "قيّمنا 12 وكالة قبل اختيار نيكسا كور. تفاهمهم مع رؤية 2030 وخبرتهم في تجربة المستخدم العربية ميزتهم تمامًا عن البقية.", name: "ليلى حسن", role: "رئيسة التحول الرقمي، مجموعة زينيث للطاقة" },
        { q: "تعاملت منصة تجارتنا الإلكترونية مع نمو ضخم في المعاملات خلال الشهر الأول بعد الإطلاق. الأداء والتصميم يعكسان توصيات ذكاء اصطناعي عالمية المستوى.", name: "يوسف الناصر", role: "المؤسس، ريتيل ويف" },
      ],
    },
    faq: {
      tag: "الأسئلة الشائعة",
      title: "أسئلة <em>متكررة</em>",
      items: [
        { q: "كم تستغرق مدة المشروع النموذجي؟", a: "تتفاوت المدة حسب النطاق. المواقع الاعتيادية 4-8 أسابيع. تطبيقات الجوال 10-16 أسبوعًا. حلول AI المؤسسية 12-24 أسبوعًا حسب متطلبات البيانات وتعقيد التكامل." },
        { q: "هل تدعمون اللغة العربية وتصميم RTL؟", a: "بالتأكيد. تصميم العربية أولاً هو جوهر ممارستنا. كل منتج نبنيه جاهز تمامًا لـRTL مع الطباعة العربية المناسبة وأنماط التصميم الثنائية اللغة." },
        { q: "هل أنتم متوافقون مع اللوائح التنظيمية المحلية؟", a: "نعم. لدينا خبرة عملية في الضوابط الأساسية للأمن السيبراني وأطر الامتثال المالي والفوترة الإلكترونية ومتطلبات إقامة البيانات للمشاريع الحكومية." },
        { q: "ما هو نموذج التسعير لديكم؟", a: "نقدم مشاريع بسعر ثابت للنطاقات المحددة جيدًا وتعاملات حسب الوقت والمواد للمتطلبات المتطورة. جميع التسعير شفاف بدون رسوم خفية." },
        { q: "هل تقدمون دعمًا بعد الإطلاق؟", a: "نعم، جميع المشاريع تشمل فترة ضمان 90 يومًا مع إصلاحات المشاكل. بعد ذلك نقدم خدمات إدارة مضمونة باتفاقيات SLA مع مراقبة 24/7." },
      ],
    },
    blog: {
      tag: "رؤى تقنية",
      title: "آخر المقالات<br>من <em>مدونتنا</em>",
      more: "عرض جميع المقالات ←",
      items: [
        { cat: "ذكاء اصطناعي", meta: "ديسمبر 2025 · 8 دقائق", title: "كيف تُعيد نماذج اللغة العربية تشكيل الخدمات الرقمية في المنطقة", exc: "نظرة داخلية على تحول الذكاء الاصطناعي الجاري عبر القطاعات المختلفة." },
        { cat: "السحابة", meta: "نوفمبر 2025 · 6 دقائق", title: "الدليل الشامل للانتقال إلى السحابة للمؤسسات في 2026", exc: "أطر ومعايير الامتثال ودروس مستفادة من أكثر من 50 مشروع ترحيل." },
        { cat: "الأمن السيبراني", meta: "نوفمبر 2025 · 5 دقائق", title: "الضوابط الأساسية للأمن السيبراني: ما يحتاج قادة التقنية معرفته", exc: "تحليل متطلبات الأمن السيبراني وكيفية تحقيق الامتثال الكامل." },
      ],
    },
    cta: {
      h2: "هل أنتم مستعدون لتحويل<br>أعمالكم بالذكاء الاصطناعي؟",
      p: "انضموا إلى أكثر من 200 مؤسسة إقليمية تبني مستقبلها الرقمي مع نيكسا كور.",
      btn1: "احجز مكالمة استراتيجية مجانية ←",
      btn2: "شاهد أعمالنا",
    },
    contact: {
      tag: "تواصل معنا",
      h2a: "لنبني شيئًا",
      h2em: "استثنائيًا",
      h2b: "معًا",
      p: "أخبرونا عن مشروعكم. سنرد خلال 24 ساعة باستراتيجية مصممة خصوصًا وعرض أسعار شفاف.",
      items: [
        { icon: "📍", h: "المقر الرئيسي", t: "طريق الملك فهد، حي العليا، الرياض 12244" },
        { icon: "📞", h: "هاتف وواتساب", t: "+966 11 XXX XXXX" },
        { icon: "✉️", h: "البريد الإلكتروني", t: "hello@nexacore.ai" },
        { icon: "🕐", h: "ساعات العمل", t: "الأحد – الخميس 8:00 ص – 6:00 م" },
      ],
      formTitle: "أرسل لنا رسالة",
      fl1: "الاسم الأول", fl2: "اسم العائلة", fl3: "البريد الإلكتروني", fl4: "الشركة", fl5: "الخدمة المطلوبة", fl6: "وصف المشروع",
      fi1: "محمد", fi2: "العتيبي", fi3: "name@company.com", fi4: "اسم شركتك",
      fi6: "أخبرونا عن أهداف مشروعكم والجدول الزمني والميزانية...",
      services: ["اختر خدمة...", "الذكاء الاصطناعي والتعلم الآلي", "تطوير البرمجيات", "تطوير المواقع", "تطبيقات الجوال", "السحابة وDevOps", "الأمن السيبراني", "أخرى"],
      submit: "إرسال الرسالة ←",
      note: "🔒 معلوماتك محفوظة بالكامل وسرية",
      submitting: "جاري الإرسال...",
      success: "شكرًا لكم! سنتواصل معكم خلال 24 ساعة.",
    },
    footer: {
      desc: "الشريك الرائد في الذكاء الاصطناعي والتحول الرقمي للمؤسسات في المنطقة. نبني مستقبل التقنية للمؤسسات منذ 2013.",
      colServices: "الخدمات",
      colSolutions: "الحلول",
      colCompany: "الشركة",
      colResources: "الموارد",
      services: ["الذكاء الاصطناعي", "تطوير البرمجيات", "تطوير المواقع", "تطبيقات الجوال", "السحابة وDevOps", "الأمن السيبراني", "تصميم UI/UX", "تحليل البيانات"],
      solutions: ["الرعاية الصحية", "المصارف والمالية", "الحوكمة", "التجزئة", "التعليم", "الطاقة", "العقارات", "التصنيع"],
      company: ["من نحن", "فريقنا", "معرض الأعمال", "دراسات الحالة", "المدونة", "الوظائف", "الصحافة والإعلام", "الشراكات"],
      resources: ["التوثيق", "مرجع API", "الأوراق البيضاء", "الندوات الإلكترونية", "سياسة الخصوصية", "شروط الخدمة", "تواصل معنا", "الدعم الفني"],
      copy: "© 2026 نيكسا كور تكنولوجي. جميع الحقوق محفوظة.",
      badges: ["ISO 27001", "SOC 2", "منصة إقليمية"],
    },
    langBarMsg: "منصة رقمية احترافية بمعايير عالمية للمنطقة",
  },

  en: {
    dir: "ltr",
    nav: {
      home: "Home",
      services: "Services",
      industries: "Industries",
      portfolio: "Portfolio",
      pricing: "Pricing",
      about: "About",
      contact: "Contact",
      cta: "Get a Free Quote",
      servicesMenu: [
        { icon: "🤖", title: "AI & Machine Learning", desc: "Custom models for content generation" },
        { icon: "💻", title: "Software Development", desc: "Bespoke enterprise applications" },
        { icon: "🌐", title: "Web Development", desc: "Stunning digital experiences" },
        { icon: "📱", title: "Mobile Apps", desc: "iOS & Android, native performance" },
        { icon: "☁️", title: "Cloud Services", desc: "AWS, Azure, Google Cloud" },
        { icon: "🔒", title: "Cybersecurity", desc: "Enterprise protection & compliance" },
        { icon: "🎨", title: "UX/UI Design", desc: "Award-winning interfaces" },
        { icon: "📊", title: "Data Analytics", desc: "Business intelligence & forecasting" },
        { icon: "⚙️", title: "ERP/CRM Systems", desc: "Enterprise systems integration" },
        { icon: "🔁", title: "DevOps & Automation", desc: "CI/CD and containerization" },
        { icon: "🚀", title: "Digital Transformation", desc: "Full enterprise modernization" },
        { icon: "🤝", title: "Tech Consulting", desc: "Strategic planning" },
      ],
      industriesMenu: [
        { icon: "🏥", title: "Healthcare", desc: "Digital health systems" },
        { icon: "🏦", title: "Banking & Finance", desc: "FinTech platforms" },
        { icon: "🏛️", title: "Government & Public Sector", desc: "Smart cities & governance" },
        { icon: "🛍️", title: "Retail & Commerce", desc: "Omnichannel platforms" },
        { icon: "🎓", title: "Education & Training", desc: "E-learning platforms" },
        { icon: "⚡", title: "Energy & Petrochemicals", desc: "Smart grid solutions" },
      ],
    },
    hero: {
      badge: "Trusted by 200+ Regional Enterprises",
      h1a: "We Build",
      h1gold: "Your Business Future",
      h1b: "with Artificial Intelligence",
      sub: "Enterprise-grade AI, cloud and digital solutions engineered for the Vision 2030 era. From intelligent automation to world-class software.",
      btn1: "Start Your Project →",
      btn2: "▶ View Our Work",
      stats: [
        { n: "200+", l: "Enterprise Clients" },
        { n: "98%", l: "Satisfaction Rate" },
        { n: "12+", l: "Years of Excellence" },
      ],
      float1: "AI Model Deployed",
      float2: "Revenue +340%",
      float3: "99.9% Uptime",
      dashTitle: "NexaCore Intelligence Dashboard",
      dml1: "AI Requests",
      dml2: "Accuracy",
      dml3: "Cost Saved",
      dch: "AI Processing Volume — Last 7 Days",
      daiTitle: "AI Assistant Active",
      daiMsg: "Anomaly detected & resolved — 3 seconds ago",
    },
    trusted: "Names Shaping the Region's Digital Economy",
    trustedSub: "A look at the institutions, ministries, and platforms driving business, finance, and public services across Saudi Arabia and the Gulf.",
    services: {
      tag: "What We Do",
      title: "End-to-End <em>Digital Excellence</em>",
      sub: "From AI to mobile apps to cloud infrastructure — every solution built for enterprise scale.",
      items: [
        { icon: "🤖", title: "AI & Machine Learning", desc: "Custom AI models for NLP, computer vision, and GenAI solutions trained on your data." },
        { icon: "💻", title: "Software Development", desc: "Enterprise applications with modern architecture — scalable, secure, future-ready." },
        { icon: "🌐", title: "Web Development", desc: "Stunning digital experiences using Next.js, React, and the latest frontend tech." },
        { icon: "📱", title: "Mobile Apps", desc: "Cross-platform iOS and Android apps users love, with native performance and design." },
        { icon: "☁️", title: "Cloud & DevOps", desc: "AWS, Azure, and GCP infrastructure with CI/CD pipelines, Kubernetes, and 99.99% SLA." },
        { icon: "🔐", title: "Cybersecurity", desc: "Penetration testing, SOC operations, and compliance frameworks for regional standards." },
        { icon: "🎨", title: "UI/UX Design", desc: "Award-winning interfaces built on user research and precise Arabic UX principles." },
        { icon: "📈", title: "Data & Analytics", desc: "BI dashboards, data warehouses, and predictive analytics at enterprise scale." },
      ],
    },
    video: {
      h2a: "Building Websites & Apps",
      h2em: "That Change the Game",
      p: "12 years of excellence in software, web and app development — 850+ projects delivered for the region's top enterprises.",
      cta: "Book a Free Consultation →",
    },
    ai: {
      tag: "AI Solutions",
      titleA: "Advanced",
      titleEm: "AI Solutions",
      titleB: "for the Regional Market",
      sub: "We deploy production-ready AI that understands Arabic language, local culture, and regional business context — not just generic model copies.",
      features: [
        { icon: "🧠", h: "Arabic-First LLMs", p: "Fine-tuned language models for Arabic dialects and MSA with local business context." },
        { icon: "👁️", h: "Computer Vision", p: "Document recognition, ID verification, infrastructure inspection — trained on regional data." },
        { icon: "⚡", h: "AI Agents & Automation", p: "Autonomous agents handling workflows, customer service, and decisions 24/7." },
        { icon: "🔮", h: "Predictive Analytics", p: "Forecasting models for demand planning, fraud detection, and risk management." },
      ],
    },
    mosaic: {
      tag: "Behind the Scenes",
      title: "A Team that Builds <em>the Extraordinary</em>",
      labels: ["Advanced Data Center", "Development Team", "Advanced AI", "Client Meetings", "Cloud Servers"],
    },
    sectors: {
      tag: "Main Sectors",
      title: "Serving the <em>Most Vital Sectors</em><br>of the Regional Economy",
      sub: "Proven expertise across 12+ sectors forming the backbone of regional economic development.",
      left: [
        { h: "Healthcare Sector", p: "Digital health systems, electronic medical records, diagnostic AI" },
        { h: "Engineering & Construction", p: "Smart project management, BIM, digital contracting platforms" },
        { h: "Legal Sector", p: "Contract automation, legal management, regulatory compliance" },
        { h: "Safety & Quality", p: "Quality management systems, smart inspection, compliance assurance" },
        { h: "Manufacturing & Industry", p: "Factory automation, industrial IoT, supply chain management" },
        { h: "Energy & Petrochemicals", p: "Operations management, grid monitoring, energy analytics" },
      ],
      right: [
        { h: "Technology & Digital Transformation", p: "AI solutions, software development, digital infrastructure" },
        { h: "Banking & Financial Services", p: "FinTech, digital banking, electronic payment systems" },
        { h: "Education & Training", p: "Smart learning platforms, LMS, interactive edtech" },
        { h: "Logistics & Transport", p: "Shipment tracking, fleet management, supply chain optimization" },
        { h: "Real Estate & Housing", p: "Property management platforms, VR tours, smart valuation" },
        { h: "Retail & eCommerce", p: "Online stores, omnichannel commerce, AI recommendations" },
      ],
    },
    industries: {
      tag: "Industries",
      title: "We Serve Every <em>Sector</em>",
      sub: "Deep domain expertise across the industries powering the regional economy.",
      items: ["Healthcare", "Finance & Banking", "Government", "Retail", "Construction", "Education", "Manufacturing", "Hospitality", "Logistics", "Energy", "Real Estate", "Telecom"],
      icons: ["🏥", "🏦", "🏛️", "🛍️", "🏗️", "🎓", "🏭", "🏨", "🚚", "⚡", "🏠", "📡"],
    },
    stats: [
      { target: 200, suffix: "+", label: "Enterprise Clients" },
      { target: 12, suffix: "+", label: "Years of Excellence" },
      { target: 850, suffix: "+", label: "Projects Delivered" },
      { target: 98, suffix: "%", label: "Satisfaction Rate" },
    ],
    values: {
      tag: "Core Values",
      title: "Principles That Guide <em>Every Decision</em>",
      sub: "Not just words on a wall — the framework that shapes every project and relationship we build.",
      items: [
        { h: "Trust & Reliability", p: "We put client interests first and commit to full transparency at every step." },
        { h: "Global Expertise", p: "A specialized team from 16+ countries combining global best practices with deep local understanding." },
        { h: "Quality & Precision", p: "From a single line of code to full transformation programs — we know quality, not guesswork." },
        { h: "Continuous Improvement", p: "We keep pace with change and adopt best practices — because technology never stops, and neither do we." },
      ],
    },
    certs: {
      tag: "Trusted Standards",
      title: "Committed to <em>the Highest Standards</em><br>of Quality & Compliance",
      sub: "International certifications and accreditations ensuring the highest levels of quality, security, and reliability.",
      items: [
        { title: "ISO 27001", sub: "Information Security Management" },
        { title: "SOC 2 Type II", sub: "Certified Security Controls" },
        { title: "Data Protection", sub: "Full Privacy Compliance" },
        { title: "PCI DSS", sub: "Payment Data Security" },
        { title: "ISO 9001", sub: "Total Quality Management" },
        { title: "Cloud Security Alliance", sub: "Cloud Computing Standards" },
        { title: "Annual Pen Testing", sub: "Independent Security Audit" },
        { title: "SLA Agreements", sub: "Guaranteed Service Levels" },
      ],
    },
    pricing: {
      tag: "Pricing Plans",
      title: "Transparent Pricing <em>for Every Business Size</em>",
      sub: "Packages built for the Saudi market — clear scope, defined deliverables, no hidden fees.",
      note: "* All prices in Saudi Riyal (SAR), excluding 15% VAT. Prices start at the listed amount and vary by project scope.",
      popular: "Most Popular",
      priceFrom: "Starting at",
      currency: "SAR",
      plans: [
        {
          name: "Starter",
          desc: "Perfect for startups and small businesses beginning their digital journey.",
          price: "12,000",
          features: [
            "Responsive professional website (up to 5 pages)",
            "Custom UI/UX design, Arabic & English",
            "Essential SEO setup",
            "3 months of cloud hosting",
            "30 days of technical support",
          ],
          cta: "Get Started",
        },
        {
          name: "Growth",
          desc: "For growing businesses that need a full platform or online store.",
          price: "35,000",
          features: [
            "Full web app or e-commerce platform",
            "Custom admin dashboard",
            "Saudi payment gateway integration (mada, STC Pay)",
            "Advanced SEO optimization",
            "6 months of support & maintenance",
          ],
          cta: "Get Started",
        },
        {
          name: "Enterprise",
          desc: "Integrated enterprise software with systems integration and scalable cloud architecture.",
          price: "95,000",
          highlight: true,
          features: [
            "Custom enterprise web/mobile application",
            "ERP/CRM systems integration",
            "Cloud architecture on AWS or Azure",
            "Cybersecurity & ISO 27001 compliance",
            "Dedicated account manager & 12-month SLA",
          ],
          cta: "Book a Consultation",
        },
        {
          name: "AI & Automation",
          desc: "Custom AI solutions — from chatbots to models trained on your own data.",
          price: "150,000",
          features: [
            "Custom Arabic-first AI / LLM models",
            "Workflow automation (RPA)",
            "Computer vision or NLP integration",
            "Predictive analytics dashboards",
            "12 months of ongoing support & training",
          ],
          cta: "Talk to an Expert",
        },
      ],
      custom: {
        title: "Need a Full Digital Transformation Program?",
        desc: "Our Enterprise+ tier is built for government entities and large organizations — fully custom project scope, a dedicated team and program manager, custom SLAs, and data residency & local compliance requirements.",
        cta: "Contact Us for a Custom Quote →",
      },
    },
    why: {
      tag: "Why NexaCore",
      title: "The Standard<br>Others <em>Aspire To</em>",
      items: [
        { n: "01", icon: "🌍", h: "Authentic Regional DNA", p: "Born and built regionally. We understand local compliance requirements and business nuances." },
        { n: "02", icon: "⚡", h: "Speed Without Compromise", p: "We ship 3x faster than traditional agencies without cutting quality. Agile from day one." },
        { n: "03", icon: "💬", h: "Research-Led Design", p: "Every interface backed by user research, A/B testing, and conversion data." },
        { n: "04", icon: "🛡️", h: "Enterprise-Grade Security", p: "ISO 27001 certified operations, SOC 2 Type II committed, pen-tested infrastructure." },
        { n: "05", icon: "🌐", h: "Global Team, Local Soul", p: "150+ engineers, designers, and AI researchers with an authentic regional culture and global standards." },
        { n: "06", icon: "🎯", h: "Dedicated, Ongoing Support", p: "A named account manager, 24/7 monitoring, and SLA-backed response times." },
      ],
    },
    team: {
      tag: "Our Team",
      title: "Global Talent<br><em>Regional Heart</em>",
      intro: "<strong>NexaCore</strong> is led by regional consultants heading a global team of talent from over <strong>16 nationalities</strong>, holding international certifications that qualify us to compete at the highest global levels.",
      countries: ["Saudi Arabia", "UAE", "Kuwait", "Bahrain", "Qatar", "Oman", "Egypt", "Lebanon", "Jordan", "United States", "United Kingdom", "Portugal", "China", "Spain", "Türkiye", "Italy", "Germany", "India"],
      flags: ["sa", "ae", "kw", "bh", "qa", "om", "eg", "lb", "jo", "us", "gb", "pt", "cn", "es", "tr", "it", "de", "in"],
      stats: [
        { n: "150+", l: "Team Members" },
        { n: "16+", l: "Nationalities" },
        { n: "45+", l: "Int'l Certifications" },
        { n: "12+", l: "Years Combined Experience" },
      ],
    },
    portfolio: {
      tag: "Portfolio",
      title: "Work That <em>Speaks</em> for Itself",
      sub: "A selection of our most impactful enterprise projects across the region.",
      featured: [
        {
          name: "Go Mobility",
          tagline: "India's #1 Driver-First Ride-Hailing App",
          tag: "Ride-Hailing · Mobile App · Delhi NCR",
          desc: "A two-sided ride-hailing marketplace built for drivers and riders alike — zero cancellation fees, live GPS tracking, SOS support, and a zero-commission driver model with capped daily platform fees. Launching across Delhi, Gurugram, Noida, Ghaziabad & Faridabad.",
          features: [
            "Zero cancellation fees & fully transparent pricing",
            "Verified drivers with 20-point vehicle checks",
            "Live GPS tracking & SOS safety support",
            "Zero-commission driver payouts, daily bank settlement",
            "24/7 Hindi-speaking driver & customer support",
          ],
          link: "https://www.gomobility.co.in/",
          linkLabel: "Visit Website →",
          qrLabel: "Scan to download the app",
          logo: "/portfolio/go-mobility-logo.jpg",
          qr: "/portfolio/go-mobility-qr.png",
        },
        {
          name: "Golden Clouds Consulting",
          tagline: "Qualifying Institutions to the Highest International Standards",
          tag: "Management Consulting · Strategy · Jeddah, KSA",
          desc: "A Saudi consulting firm with 30+ years of experience helping institutions scale across strategy, governance, and human capital — backed by 130+ strategic partnerships and alliances with Deloitte, PwC, EY, and KPMG.",
          features: [
            "100+ years of combined consulting experience",
            "Global team across 16+ nationalities, 9+ languages",
            "130+ strategic partnerships worldwide",
            "Aligned with Saudi Vision 2030 government programs",
            "Presence across 10+ countries",
          ],
          link: "https://gccso.com/en/",
          linkLabel: "Visit Website →",
          logo: "/portfolio/golden-clouds-consulting.jpg",
        },
        {
          name: "Smart Homes",
          tagline: "Own Intelligence — Transforming Buildings into Smart Spaces",
          tag: "Smart Home Automation · IoT · Saudi Arabia",
          desc: "A Saudi smart-building specialist delivering home automation, centralized vacuum and gas systems, solar water heating, and AI-integrated security — deployed across 6,000+ residential units and 13+ regions in the Kingdom.",
          features: [
            "45,000+ smart products installed nationwide",
            "6,000+ residential units converted to smart homes",
            "5,000+ centralized vacuum systems deployed",
            "Encrypted 24/7 security camera monitoring",
            "5+ branches across Saudi Arabia",
          ],
          link: "https://www.smarthomes.sa/",
          linkLabel: "Visit Website →",
          logo: "/portfolio/smart-homes.jpg",
        },
      ],
      items: [
        { tag: "FinTech · AI", name: "Digital Banking Platform — Confidential Client", icon: "🏦", desc: "A full digital banking suite with AI fraud detection and personalized financial recommendations." },
        { tag: "Healthcare · Mobile", name: "National Health App — Confidential Client", icon: "🏥", desc: "A national mobile app connecting patients to facilities, appointment booking, and e-health records." },
        { tag: "Smart City · IoT", name: "Smart Infrastructure AI — Confidential Client", icon: "🏙️", desc: "An IoT sensor network with AI analytics for real-time traffic, energy, and urban service management." },
        { tag: "Energy · Analytics", name: "Energy Operations Dashboard — Confidential Client", icon: "⚡", desc: "A unified operations dashboard for grid monitoring, plant performance, and predictive maintenance." },
        { tag: "EdTech · LMS", name: "National Learning Platform — Confidential Client", icon: "📚", desc: "A multilingual e-learning platform serving hundreds of thousands of students with interactive content." },
        { tag: "Retail · eCommerce", name: "Regional Omnichannel Platform — Confidential Client", icon: "🛒", desc: "A unified commerce platform combining online storefront, POS, and inventory into a single system." },
        { tag: "Logistics · Fleet Tracking", name: "Fleet & Logistics Management Platform — Confidential Client", icon: "🚚", desc: "A live fleet-tracking system with AI route optimization and regional supply chain management." },
      ],
    },
    process: {
      tag: "How We Work",
      title: "Our <em>Proven</em> Process",
      sub: "A refined delivery framework trusted by 200+ enterprises — from first call to final launch.",
      steps: [
        { icon: "🔍", h: "Discovery", p: "Deep requirements, stakeholder interviews, technical audit, and market research." },
        { icon: "✏️", h: "Strategy & Design", p: "Architecture, wireframes, design system, and prototype sign-off." },
        { icon: "⚙️", h: "Development", p: "Agile sprints, weekly demos, code reviews, continuous integration." },
        { icon: "🧪", h: "Quality Assurance", p: "Performance, security, cross-device, and UAT with real users." },
        { icon: "🚀", h: "Launch & Growth", p: "Go-live, monitoring, optimization, and ongoing partnership." },
      ],
    },
    tech: {
      tag: "Technology",
      title: "Built with the <em>Best Tools Available</em>",
      sub: "From the front-end to server-side infrastructure — a modern, production-tested stack spanning servers, databases, and enterprise-grade DevOps.",
      hubLabel: "Core Stack",
      hubHint: "Scroll to see how it all connects ←",
      categories: {
        all: "All",
        frontend: "Frontend",
        backend: "Backend & Server-Side",
        database: "Databases",
        cloud: "Cloud & DevOps",
        ai: "AI & ML",
      },
    },
    testimonials: {
      tag: "Client Testimonials",
      title: "What Our <em>Clients</em> Say",
      items: [
        { q: "NexaCore completely transformed our digital operations. The AI solution they built reduced our processing time by 80% with unmatched accuracy. A truly enterprise-grade team.", name: "Ahmed Al-Fahad", role: "CTO, Falcon Holdings Group" },
        { q: "We evaluated 12 agencies before choosing NexaCore. Their alignment with regional digital strategy and Arabic UX expertise set them apart entirely.", name: "Layla Hassan", role: "Head of Digital Transformation, Zenith Energy Group" },
        { q: "Our eCommerce platform handled massive transaction growth in the first month post-launch. Performance and design reflect world-class AI recommendations.", name: "Yousef Al-Nasser", role: "Founder, RetailWave" },
      ],
    },
    faq: {
      tag: "FAQ",
      title: "Frequently Asked <em>Questions</em>",
      items: [
        { q: "How long does a typical project take?", a: "Timelines vary by scope. Standard websites: 4-8 weeks. Mobile apps: 10-16 weeks. Enterprise AI solutions: 12-24 weeks depending on data requirements and integration complexity." },
        { q: "Do you support Arabic and RTL design?", a: "Absolutely. Arabic-first is core to our practice. Every product we build is fully RTL-ready with proper Arabic typography and bilingual design patterns." },
        { q: "Are you compliant with local regulations?", a: "Yes. We have hands-on experience with essential cybersecurity controls, financial compliance frameworks, e-invoicing regulations, and data residency requirements for government projects." },
        { q: "What is your pricing model?", a: "We offer fixed-price projects for well-defined scopes and time-and-materials engagements for evolving requirements. All pricing is transparent with no hidden fees." },
        { q: "Do you provide post-launch support?", a: "Yes, all projects include a 90-day warranty period with bug fixes. After that we offer SLA-backed managed services with 24/7 monitoring." },
      ],
    },
    blog: {
      tag: "Insights",
      title: "Latest from<br><em>Our Blog</em>",
      more: "View All Articles →",
      items: [
        { cat: "AI", meta: "December 2025 · 8 min read", title: "How Arabic LLMs Are Reshaping Digital Services Across the Region", exc: "An inside look at the ongoing AI transformation across sectors." },
        { cat: "Cloud", meta: "November 2025 · 6 min read", title: "The Complete Guide to Enterprise Cloud Migration in 2026", exc: "Frameworks, compliance, and real-world lessons from 50+ migrations." },
        { cat: "Cybersecurity", meta: "November 2025 · 5 min read", title: "Essential Cybersecurity Controls Every Tech Leader Should Know", exc: "Breaking down regulatory security requirements and how to achieve compliance." },
      ],
    },
    cta: {
      h2: "Ready to Transform<br>Your Business with AI?",
      p: "Join 200+ regional enterprises already building their digital future with NexaCore.",
      btn1: "Get a Free Strategy Call →",
      btn2: "View Our Work",
    },
    contact: {
      tag: "Contact Us",
      h2a: "Let's Build Something",
      h2em: "Extraordinary",
      h2b: "Together",
      p: "Tell us about your project. We'll respond within 24 hours with a tailored strategy and transparent quote.",
      items: [
        { icon: "📍", h: "Headquarters", t: "King Fahd Road, Al Olaya District, Riyadh 12244" },
        { icon: "📞", h: "Phone & WhatsApp", t: "+966 11 XXX XXXX" },
        { icon: "✉️", h: "Email", t: "hello@nexacore.ai" },
        { icon: "🕐", h: "Business Hours", t: "Sun–Thu 8:00 AM – 6:00 PM" },
      ],
      formTitle: "Send Us a Message",
      fl1: "First Name", fl2: "Last Name", fl3: "Email Address", fl4: "Company", fl5: "Service Interest", fl6: "Project Brief",
      fi1: "Mohammed", fi2: "Al-Otaibi", fi3: "name@company.com", fi4: "Your Company Name",
      fi6: "Tell us about your project goals, timeline, and budget...",
      services: ["Select a service...", "AI & Machine Learning", "Software Development", "Web Development", "Mobile Apps", "Cloud & DevOps", "Cybersecurity", "Other"],
      submit: "Send Message →",
      note: "🔒 Your information is 100% confidential",
      submitting: "Sending...",
      success: "Thank you! We'll get back to you within 24 hours.",
    },
    footer: {
      desc: "A leading AI and digital transformation partner for regional enterprises. Building enterprise technology since 2013.",
      colServices: "Services",
      colSolutions: "Solutions",
      colCompany: "Company",
      colResources: "Resources",
      services: ["AI Solutions", "Software Dev", "Web Development", "Mobile Apps", "Cloud & DevOps", "Cybersecurity", "UI/UX Design", "Data Analytics"],
      solutions: ["Healthcare", "Finance", "Government", "Retail", "Education", "Energy", "Real Estate", "Manufacturing"],
      company: ["About Us", "Our Team", "Portfolio", "Case Studies", "Blog", "Careers", "Press", "Partners"],
      resources: ["Documentation", "API Reference", "Whitepapers", "Webinars", "Privacy Policy", "Terms", "Contact", "Support"],
      copy: "© 2026 NexaCore Technologies. All rights reserved.",
      badges: ["ISO 27001", "SOC 2", "Regional Platform"],
    },
    langBarMsg: "Professional Digital Platform for the Region",
  },
};
